[package]
name = "air-lambda-ast"
description = "Definition of the AIR lambda AST"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/fluencelabs/aquavm"
documentation = "https://docs.rs/air-lambda-ast"
keywords = ["fluence", "air", "lambda", "ast"]
categories = ["wasm"]

[lib]
name = "air_lambda_ast"
path = "src/lib.rs"

[dependencies]
non-empty-vec = { version = "0.2.3", features = ["serde"] }
itertools = "0.10.5"

serde = { version = "1.0.164", features = ["rc", "derive"] }
serde_json = "1.0.95"
