[toolchain]
# AquaVM can be built with "stable", "nightly" required only to build Marine tests
channel = "nightly-2022-11-01"
components = [ "rustfmt", "clippy", "rust-src", "llvm-tools-preview" ]
targets = [ "x86_64-unknown-linux-gnu", "x86_64-apple-darwin", "wasm32-wasi", "wasm32-unknown-unknown" ]
profile = "minimal"
