[package]
name = "air-utils"
version = "0.1.1"
description = "AIR helper funcitions and macros"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
keywords = ["fluence", "air", "webassembly", "programming-language"]
categories = ["wasm"]

[lib]
name = "air_utils"
path = "src/lib.rs"
