[package]
name = "air-trace-handler"
version = "0.1.3"
description = "Implementation of AIR trace handler"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
keywords = ["fluence", "air", "webassembly", "programming-language"]
categories = ["wasm"]

[lib]
name = "air_trace_handler"
path = "src/lib.rs"

[dependencies]
air-interpreter-cid = { version = "0.2.0", path = "../interpreter-cid" }
air-interpreter-data = { version = "0.6.4", path = "../interpreter-data" }
air-interpreter-interface = { version = "0.13.0", path = "../interpreter-interface" }
air-log-targets = { version = "0.1.0", path = "../log-targets" }
aquavm-air-parser = { version = "0.7.4", path = "../air-parser" }
polyplets = { version = "0.3.2", path = "../polyplets" }

bimap = "0.6.2"
serde_json = "1.0.94"
log = "0.4.17"
thiserror = "1.0.39"
tracing = "0.1.37"
